const data = [
    { img1: "https://i.ibb.co/2K12Km4/langing-icons.png", img2: "https://i.ibb.co/mB3H5Wr/akin-cakiner-Egfq-SH9y-Lqg-unsplash.jpg", img3: "https://i.ibb.co/4fQq4M4/aaron-burden-y-Fn-X8-Da-C3-UM-unsplash-1.jpg" },
    { name: "U49WF FPV Camera Drone.", price: 150, describe: "INCLUDES: U49WF Wi-Fi Drone, 720p HD Camera, 2.4Ghz Remote Controller, 7.4V 1000mAh LI-PO Battery (2), USB Charger Cable, Micro USB Cable, User Manual, Extra Propellers (4), Drone ToolsEASY TO FLY: U49WF comes fully loaded with 3 speeds and 1-key take off and landing to make drone flying a breeze. Also equipped with superior safety features like an out of range alarm and bumpers.LONGER FLIGHT TIME: Enjoy flying the U49W for up to 25 minutes total flying time with the extra drone battery.", img: "https://i.ibb.co/r53s0Cx/vlad-busuioc-W0bf1-NJPPLM-unsplash.jpg" },
    { name: "Holy Stone HS270 2.7k Drone..", price: 200, describe: "2.7 K Camera & 5G Image Transmission -- 2.7K HD camera catches incredible clarity in the photos; 5G transmission ensures beautiful scenes are sent back to the phone, frequent and clear; 90°adjustable angle enables broader views. You may also share your laughter on social media from Holy Stone App page directly and easily.", img: "https://i.ibb.co/0fMy0Ym/michael-parulava-nq-b-BBOA5y-E-unsplash.jpg" },
    { name: "DJI Mavic Air 2.", price: 210, describe: "Mavic Air 2 takes power and portability to the next level, offering advanced features in a compact form factor. Intelligent shooting functions and excellent image quality put aerial masterpieces within reach. Safer, smarter flight enables you to up your game while fully enjoying the creative process.INCLUDES: U49WF Wi-Fi Drone, 720p HD Camera, 2.4Ghz Remote Controller, 7.4V 1000mAh LI-PO Battery (2), USB Charger Cable, Micro USB Cable, User Manual, Extra Propellers (4), Drone ToolsEASY TO FLY: U49WF comes fully loaded with 3 speeds and 1-key take off and landing to make drone flying a breeze. Also equipped with superior safety features like an out of range alarm and bumpers.LONGER FLIGHT TIME: Enjoy flying the U49W for up to 25 minutes total flying time with the extra drone battery.", img: "https://i.ibb.co/nmL0yZh/matthew-lejune-Py-Achlfq21k-unsplash.jpg" },
    { name: "Skydio 2.", price: 180, describe: "We recently announced Skydio 3D Scan™, a first-of-its-kind adaptive scanning software for autonomous 3D capture of any structure or scene with comprehensive coverage and ultra-high resolution. Watch our launch event where Adam Bry (CEO), Alden Jones (VP of Customer Success), and Hayk Martiros (VP of Autonomy) unveiled 3D Scan to the world from the U.S. Space & Rocket Center in Huntsville, AL. ", img: "https://i.ibb.co/vLTZCgk/bruno-yamazaky-Qo-JR8-SVkf-RM-unsplash.jpg" },
    { name: "DJI FPV Drone.", price: 210, describe: "DJI FPV stands out in more ways than one. Sporting front LEDs and aircraft arm lights with customizable-color, DJI FPV allows pilots to make their aircraft as unique as they are.", img: "https://i.ibb.co/nmL0yZh/matthew-lejune-Py-Achlfq21k-unsplash.jpg" },
    { name: "Autel Evo II Series.", price: 250, describe: "With an 8K camera payload, the EVO II 8K can capture video at up to 7680 x 4320 resolution (8000 x 6000 stills). This lets you make prints up to 100 wide, punch in, crop, and scale images with great detail, and capture stunning hi-res screenshots from your footage.", img: "https://i.ibb.co/9t2bj5J/joshua-kantarges-g-By985-PKkp-Q-unsplash.jpg" },
    { name: "DJI Mavic 2 Zoom.", price: 300, describe: "The Mavic 2 Zoom from DJI is a professional quality filmmaking drone that gives you the ability to get closer to the action, thanks to its 2x 24-48mm optical zoom camera with a 1/2.3 12MP sensor. With 4x lossless zoom (including 2x optical zoom) you can capture sensitive subjects from an even greater distance. There's even a single-tap aerial mode called Dolly Zoom that gives a Hitchcockian effect to your footage.", img: "https://i.ibb.co/gWng1ny/billy-freeman-s-Myxd6-Ytm-Bg-unsplash.jpg" },
    { name: "DJI Mavic 2 Pro.", price: 250, describe: "The Mavic 2 Pro from DJI is a drone that balances power, portability, and professional-quality visuals with the inclusion of a 20MP Hasselblad L1D-20c gimbal camera. ... There's also omnidirectional obstacle sensing that provides object avoidance with sensors on all sides of the Mavic 2 Pro.", img: "https://i.ibb.co/9t2bj5J/joshua-kantarges-g-By985-PKkp-Q-unsplash.jpg" },
    { name: "DJI Phantom 4 Pro V2.0.", price: 200, describe: "Featuring a 1-inch CMOS sensor that can shoot 4K/60fps videos and 20MP photos, the Phantom 4 Pro V2.0 grants filmmakers absolute creative freedom. The OcuSync 2.0 HD transmission system ensures stable connectivity and reliability, five directions of obstacle sensing ensures additional safety, and a dedicated remote controller with a built-in screen grants even greater precision and control. [1] A wide array of intelligent features makes flying that much easier. The Phantom 4 Pro V2.0 is a complete aerial imaging solution, designed for the professional creator.", img: "https://i.ibb.co/m4CQQRD/annie-spratt-I9-Ta-Ts-U-Vn-E-unsplash.jpg" },
    { name: "DJI Mavic 2 Zoom.", price: 300, describe: "The Mavic 2 Zoom from DJI is a professional quality filmmaking drone that gives you the ability to get closer to the action, thanks to its 2x 24-48mm optical zoom camera with a 1/2.3 12MP sensor. With 4x lossless zoom (including 2x optical zoom) you can capture sensitive subjects from an even greater distance. There's even a single-tap aerial mode called Dolly Zoom that gives a Hitchcockian effect to your footage.", img: "https://i.ibb.co/gWng1ny/billy-freeman-s-Myxd6-Ytm-Bg-unsplash.jpg" }
]



